on:
  pull_request:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: lemonenergy/release-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
