on:
  pull_request:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: bump version and merge it on develop
        uses: lemonenergy/release-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
